// =================================
// DOM ELEMENTS
// =================================

const searchInput =
    document.getElementById("searchInput");

const searchButton =
    document.getElementById("searchButton");

const answerTitle =
    document.getElementById("answerTitle");

const answerText =
    document.getElementById("answerText");

const answerDetails =
    document.getElementById("answerDetails");

const officialSource =
    document.getElementById("officialSource");

const officialDescription =
    document.getElementById("officialDescription");

const researchSource =
    document.getElementById("researchSource");

const researchDescription =
    document.getElementById("researchDescription");

const actionTitle =
    document.getElementById("actionTitle");

const actionDescription =
    document.getElementById("actionDescription");

const roadmapButton =
    document.getElementById("roadmapButton");

const verifySourcesButton =
    document.getElementById("verifySourcesButton");


// =================================
// NEXORA USER
// =================================

function getNexoraUserId() {

    const userId =
        localStorage.getItem("nexoraUserId");

    return userId || null;
}


// =================================
// SEARCH BUTTON
// =================================

searchButton.addEventListener(
    "click",
    performSearch
);


// =================================
// ENTER KEY SEARCH
// =================================

searchInput.addEventListener(
    "keydown",
    function (event) {

        if (event.key === "Enter") {

            performSearch();

        }

    }
);


// =================================
// MAIN SEARCH
// =================================

async function performSearch() {

    const query =
        searchInput.value.trim();


    if (query === "") {

        alert("Please enter a question.");

        return;

    }


    // Save local history

    saveSearchHistory(query);


    // Loading

    answerTitle.textContent =
        "NEXORA is searching...";

    answerText.textContent =
        "Searching the web and processing your question...";

    answerDetails.textContent =
        "Connecting to NEXORA AI and Tavily Web Search.";


    // Run AI + Search

    


await Promise.all([

    askNexoraBackend(query),

    searchWeb(query),

    searchBestVideo(query)

]);

}


// =================================
// ASK NEXORA
// =================================

async function askNexoraBackend(question) {

    try {

        const userId =
            getNexoraUserId();


        const response =
            await fetch(
                (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
    ? "http://localhost:5000"
    : "https://nexora-o8wi.onrender.com") + "/api/ask",
                {

                    method: "POST",

                    headers: {

                        "Content-Type":
                            "application/json"

                    },

                    body: JSON.stringify({

                        question: question,

                        userId: userId

                    })

                }
            );


        const data =
            await response.json();


        if (!response.ok || !data.success) {

            throw new Error(

                data.message ||

                "AI request failed"

            );

        }


        // =================================
        // AI ANSWER
        // =================================

        answerTitle.textContent =
            question;

        answerText.textContent =
            data.answer ||

            "NEXORA could not generate an answer.";

        answerDetails.textContent =
            "Answer generated by NEXORA Local AI using " +

            data.model;


        // =================================
        // ACTION
        // =================================

        actionTitle.textContent =
            "What can you do with this information?";

        actionDescription.textContent =
            "NEXORA can help you research this topic, " +

            "verify sources and create a learning roadmap.";


    } catch (error) {

        console.error(
            "NEXORA AI Error:",
            error
        );


        answerTitle.textContent =
            question;

        answerText.textContent =
            "NEXORA AI could not generate an answer.";

        answerDetails.textContent =
            "Make sure Ollama and the NEXORA backend are running.";

    }

}

// =================================
// BEST VIDEO SEARCH
// =================================

async function searchBestVideo(query) {

    try {

        const baseUrl =
            (window.location.hostname === "localhost" ||
             window.location.hostname === "127.0.0.1")
                ? "http://localhost:5000"
                : "https://nexora-o8wi.onrender.com";

        const response =
            await fetch(
                baseUrl +
                "/api/video?q=" +
                encodeURIComponent(query)
            );

        const data =
            await response.json();

        if (!response.ok || !data.success) {

            throw new Error(
                data.message ||
                "Video search failed"
            );

        }

        console.log(
            "NEXORA Best Video:",
            data.video
        );

        if (data.video) {

            displayBestVideo(
                data.video
            );

        }

    } catch (error) {

        console.error(
            "NEXORA Video Search Error:",
            error
        );

    }

}
// =================================
// DISPLAY BEST VIDEO
// =================================

function displayBestVideo(video) {

    const videoSection =
        document.getElementById("bestVideoSection");

    const videoTitle =
        document.getElementById("bestVideoTitle");

    const videoDescription =
        document.getElementById("bestVideoDescription");

    const videoLink =
        document.getElementById("bestVideoLink");


    if (
        !videoSection ||
        !videoTitle ||
        !videoDescription ||
        !videoLink
    ) {

        console.error(
            "Best Video elements not found."
        );

        return;

    }


    videoTitle.textContent =
        video.title ||
        "Best Video";


    videoDescription.textContent =
        video.content
            ? video.content.slice(0, 180)
            : "A relevant video for this topic.";


    videoLink.href =
        video.url || "#";


    videoSection.style.display =
        "block";

}
// =================================
// TAVILY WEB SEARCH
// =================================

async function searchWeb(query) {

    try {

        const userId =
            getNexoraUserId();


        const response =
            await fetch(

                (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
    ? "http://localhost:5000"
    : "https://nexora-o8wi.onrender.com") + "/api/search?q=" +

                encodeURIComponent(query) +

                "&userId=" +

                encodeURIComponent(userId || "")

            );


        const data =
            await response.json();


        if (!response.ok || !data.success) {

            throw new Error(

                data.message ||

                "Web search failed"

            );

        }


        console.log(
            "Tavily Results:",
            data.sources
        );


        // Display sources

        displaySources(
            data.sources || []
        );


    } catch (error) {

        console.error(
            "NEXORA Web Search Error:",
            error
        );


        showSourceError();

    }

}


// =================================
// DISPLAY SOURCES
// =================================

function displaySources(sources) {

    if (
        !sources ||
        sources.length === 0
    ) {

        officialSource.textContent =
            "No sources found";

        officialDescription.textContent =
            "NEXORA could not find web sources for this search.";

        researchSource.textContent =
            "No research sources";

        researchDescription.textContent =
            "Try a different search query.";

        return;

    }


    // =================================
    // FIRST SOURCE
    // =================================

    const first =
        sources[0];


    officialSource.textContent =
        first.title ||

        "Web Source";


    officialDescription.textContent =
        first.content ||

        first.url ||

        "No description available.";


    makeSourceClickable(
        officialSource,
        first.url
    );


    // =================================
    // SECOND SOURCE
    // =================================

    if (sources.length > 1) {

        const second =
            sources[1];


        researchSource.textContent =
            second.title ||

            "Research Source";


        researchDescription.textContent =
            second.content ||

            second.url ||

            "No description available.";


        makeSourceClickable(
            researchSource,
            second.url
        );

    }


    // Remaining sources

    addAdditionalSources(
        sources.slice(2)
    );

}


// =================================
// CLICKABLE SOURCE
// =================================

function makeSourceClickable(
    element,
    url
) {

    if (!url) {

        return;

    }


    element.style.cursor =
        "pointer";


    element.title =
        "Open source";


    element.onclick =
        function () {

            window.open(

                url,

                "_blank",

                "noopener,noreferrer"

            );

        };

}


// =================================
// ADDITIONAL SOURCES
// =================================

function addAdditionalSources(sources) {

    const sourcesSection =
        document.querySelector(
            ".sources-section"
        );


    if (!sourcesSection) {

        return;

    }


    // Remove old cards

    document
        .querySelectorAll(
            ".nexora-extra-source"
        )
        .forEach(
            card => card.remove()
        );


    sources.forEach(
        function (source) {

            const card =
                document.createElement("div");


            card.className =
                "source-card nexora-extra-source";


            const container =
                document.createElement("div");


            const type =
                document.createElement("span");


            type.className =
                "source-type";


            type.textContent =
                source.sourceType ||

                "Web Source";


            const title =
                document.createElement("h3");


            title.textContent =
                source.title ||

                "Untitled Source";


            const description =
                document.createElement("p");


            description.textContent =
                source.content ||

                source.url ||

                "No description available.";


            if (source.url) {

                title.style.cursor =
                    "pointer";


                title.title =
                    "Open source";


                title.onclick =
                    function () {

                        window.open(

                            source.url,

                            "_blank",

                            "noopener,noreferrer"

                        );

                    };

            }


            container.appendChild(type);

            container.appendChild(title);

            container.appendChild(description);

            card.appendChild(container);


            sourcesSection.appendChild(card);

        }
    );

}


// =================================
// SOURCE ERROR
// =================================

function showSourceError() {

    officialSource.textContent =
        "Web Search Error";


    officialDescription.textContent =
        "NEXORA could not load web sources. " +

        "Make sure the backend is running.";


    researchSource.textContent =
        "Tavily unavailable";


    researchDescription.textContent =
        "Please check the NEXORA backend.";

}


// =================================
// LEARNING ROADMAP
// =================================

if (roadmapButton) {

    roadmapButton.addEventListener(

        "click",

        function () {

            const topic =
                searchInput.value.trim();


            if (topic === "") {

                alert(
                    "Please search for a topic first."
                );

                return;

            }


            window.location.href =
                "roadmap.html?topic=" +

                encodeURIComponent(topic);

        }

    );

}


// =================================
// VERIFY SOURCES
// =================================

if (verifySourcesButton) {

    verifySourcesButton.addEventListener(

        "click",

        function () {

            const topic =
                searchInput.value.trim();


            if (topic === "") {

                alert(
                    "Please search for a topic first."
                );

                return;

            }


            window.location.href =
                "verify.html?topic=" +

                encodeURIComponent(topic);

        }

    );

}


// =================================
// LOCAL SEARCH HISTORY
// =================================

function saveSearchHistory(query) {

    let history =
        JSON.parse(

            localStorage.getItem(
                "nexoraSearchHistory"
            )

        ) || [];


    history.unshift(query);


    history =
        history.slice(0, 10);


    localStorage.setItem(

        "nexoraSearchHistory",

        JSON.stringify(history)

    );


    localStorage.setItem(

        "nexoraSearchCount",

        history.length

    );

}


// =================================
// DEBUG USER
// =================================

console.log(
    "NEXORA User ID:",
    getNexoraUserId()
);