
// =================================
// DOM ELEMENTS

// =================================

const searchInput =
    document.getElementById("searchInput");

const searchButton =
    document.getElementById("searchButton");

const answerTitle =
    document.getElementById("answerTitle");

const answerText =
    document.getElementById("answerText");

const answerDetails =
    document.getElementById("answerDetails");

const officialSource =
    document.getElementById("officialSource");

const officialDescription =
    document.getElementById("officialDescription");

const researchSource =
    document.getElementById("researchSource");

const researchDescription =
    document.getElementById("researchDescription");

const actionTitle =
    document.getElementById("actionTitle");

const actionDescription =
    document.getElementById("actionDescription");

const roadmapButton =
    document.getElementById("roadmapButton");

const verifySourcesButton =
    document.getElementById("verifySourcesButton");



// =================================
// NEXORA USER

// =================================

function getNexoraUserId() {

    const userId =
        localStorage.getItem("nexoraUserId");

    return userId || null;
}



// =================================
// SEARCH BUTTON

// =================================

searchButton.addEventListener(
    "click",
    performSearch
);



// =================================
// ENTER KEY SEARCH

// =================================

searchInput.addEventListener(
    "keydown",
    function (event) {

        if (event.key === "Enter") {

            performSearch();

        }

    }
);



// =================================
// MAIN SEARCH

// =================================

async function performSearch() {

    const query =
        searchInput.value.trim();


    if (query === "") {

        alert("Please enter a question.");

        return;

    }


    // Save local history

    saveSearchHistory(query);


    // Loading

    answerTitle.textContent =
        "NEXORA is searching...";

    answerText.textContent =
        "Searching the web and processing your question...";

    answerDetails.textContent =
        "Connecting to NEXORA AI and Tavily Web Search.";


    // Run AI + Search

    


await Promise.all([

    askNexoraBackend(query),

    searchWeb(query),

    searchBestVideo(query)

]);

}



// =================================
// ASK NEXORA

// =================================

async function askNexoraBackend(question) {

    try {

        const userId =
            getNexoraUserId();


        const response =
            await fetch(
                (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
    ? "http://localhost:5000"
    : "https://nexora-o8wi.onrender.com") + "/api/ask",
                {

                    method: "POST",

                    headers: {

                        "Content-Type":
                            "application/json"

                    },

                    body: JSON.stringify({

                        question: question,

                        userId: userId

                    })

                }
            );


        const data =
            await response.json();


        if (!response.ok || !data.success) {

            throw new Error(

                data.message ||

                "AI request failed"

            );

        }



        // =================================
        // AI ANSWER

        // =================================

        answerTitle.textContent =
            question;

        answerText.textContent =
            data.answer ||

            "NEXORA could not generate an answer.";

        answerDetails.textContent =
            "Answer generated by NEXORA Local AI using " +

            data.model;



        // =================================
        // ACTION

        // =================================

        actionTitle.textContent =
            "What can you do with this information?";

        actionDescription.textContent =
            "NEXORA can help you research this topic, " +

            "verify sources and create a learning roadmap.";


    } catch (error) {

        console.error(
            "NEXORA AI Error:",
            error
        );


        answerTitle.textContent =
            question;

        answerText.textContent =
            "NEXORA AI could not process the answer.\n\nPlease try again or check the NEXORA backend logs."; 

    }

}


// =================================
// BEST VIDEO SEARCH

// =================================

async function searchBestVideo(query) {

    try {

        const baseUrl =
            (window.location.hostname === "localhost" ||
             window.location.hostname === "127.0.0.1")
                ? "http://localhost:5000"
                : "https://nexora-o8wi.onrender.com";

        const response =
            await fetch(
                baseUrl +
                "/api/video?q=" +
                encodeURIComponent(query)
            );

        const data =
            await response.json();

        if (!response.ok || !data.success) {

            throw new Error(
                data.message ||
                "Video search failed"
            );

        }

        console.log(
            "NEXORA Best Video:",
            data.video
        );

        if (data.video) {

            displayBestVideo(
                data.video
            );

        }

    } catch (error) {

        console.error(
            "NEXORA Video Search Error:",
            error
        );

    }

}

// =================================
// DISPLAY BEST VIDEO

// =================================

function displayBestVideo(video) {

    const videoSection =
        document.getElementById("bestVideoSection");

    const videoTitle =
        document.getElementById("bestVideoTitle");

    const videoDescription =
        document.getElementById("bestVideoDescription");

    const videoLink =
        document.getElementById("bestVideoLink");


    if (
        !videoSection ||
        !videoTitle ||
        !videoDescription ||
        !videoLink
    ) {

        console.error(
            "Best Video elements not found."
        );

        return;

    }


    videoTitle.textContent =
        video.title ||
        "Best Video";


    videoDescription.textContent =
        video.content
            ? video.content.slice(0, 180)
            : "A relevant video for this topic.";


    videoLink.href =
        video.url || "#";


    videoSection.style.display =
        "block";

}

// =================================
// TAVILY WEB SEARCH

// =================================

async function searchWeb(query) {

    try {

        const userId =
            getNexoraUserId();


        const response =
            await fetch(

                (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
    ? "http://localhost:5000"
    : "https://nexora-o8wi.onrender.com") + "/api/search?q=" +

                encodeURIComponent(query) +

                "&userId=" +

                encodeURIComponent(userId || "")

            );


        const data =
            await response.json();


        if (!response.ok || !data.success) {

            throw new Error(

                data.message ||

                "Web search failed"

            );

        }


        console.log(
            "Tavily Results:",
            data.sources
        );


        // Display sources

        displaySources(
            data.sources || []
        );


    } catch (error) {

        console.error(
            "NEXORA Web Search Error:",
            error
        );


        showSourceError();

    }

}



// =================================
// DISPLAY SOURCES

// =================================

function displaySources(sources) {

    if (
        !sources ||
        sources.length === 0
    ) {

        officialSource.textContent =
            "No sources found";

        officialDescription.textContent =
            "NEXORA could not find web sources for this search.";

        researchSource.textContent =
            "No research sources";

        researchDescription.textContent =
            "Try a different search query.";

        return;

    }



    // =================================
    // FIRST SOURCE

    // =================================

    const first =
        sources[0];


    officialSource.textContent =
        first.title ||

        "Web Source";


    officialDescription.textContent =
        first.content ||

        first.url ||

        "No description available.";


    makeSourceClickable(
        officialSource,
        first.url
    );



    // =================================
    // SECOND SOURCE

    // =================================

    if (sources.length > 1) {

        const second =
            sources[1];


        researchSource.textContent =
            second.title ||

            "Research Source";


        researchDescription.textContent =
            second.content ||

            second.url ||

            "No description available.";


        makeSourceClickable(
            researchSource,
            second.url
        );

    }


    // Remaining sources

    addAdditionalSources(
        sources.slice(2)
    );

}



// =================================
// CLICKABLE SOURCE

// =================================

function makeSourceClickable(
    element,
    url
) {

    if (!url) {

        return;

    }


    element.style.cursor =
        "pointer";


    element.title =
        "Open source";


    element.onclick =
        function () {

            window.open(

                url,

                "_blank",

                "noopener,noreferrer"

            );

        };

}



// =================================
// ADDITIONAL SOURCES

// =================================

function addAdditionalSources(sources) {

    const sourcesSection =
        document.querySelector(
            ".sources-section"
        );


    if (!sourcesSection) {

        return;

    }


    // Remove old cards

    document
        .querySelectorAll(
            ".nexora-extra-source"
        )
        .forEach(
            card => card.remove()
        );


    sources.forEach(
        function (source) {

            const card =
                document.createElement("div");


            card.className =
                "source-card nexora-extra-source";


            const container =
                document.createElement("div");


            const type =
                document.createElement("span");


            type.className =
                "source-type";


            type.textContent =
                source.sourceType ||

                "Web Source";


            const title =
                document.createElement("h3");


            title.textContent =
                source.title ||

                "Untitled Source";


            const description =
                document.createElement("p");


            description.textContent =
                source.content ||

                source.url ||

                "No description available.";


            if (source.url) {

                title.style.cursor =
                    "pointer";


                title.title =
                    "Open source";


                title.onclick =
                    function () {

                        window.open(

                            source.url,

                            "_blank",

                            "noopener,noreferrer"

                        );

                    };

            }


            container.appendChild(type);

            container.appendChild(title);

            container.appendChild(description);

            card.appendChild(container);


            sourcesSection.appendChild(card);

        }
    );

}



// =================================
// SOURCE ERROR

// =================================

function showSourceError() {

    officialSource.textContent =
        "Web Search Error";


    officialDescription.textContent =
        "NEXORA could not load web sources. " +

        "Make sure the backend is running.";


    researchSource.textContent =
        "Tavily unavailable";


    researchDescription.textContent =
        "Please check the NEXORA backend.";

}



// =================================
// LEARNING ROADMAP

// =================================

if (roadmapButton) {

    roadmapButton.addEventListener(

        "click",

        function () {

            const topic =
                searchInput.value.trim();


            if (topic === "") {

                alert(
                    "Please search for a topic first."
                );

                return;

            }


            window.location.href =
                "roadmap.html?topic=" +

                encodeURIComponent(topic);

        }

    );

}



// =================================
// VERIFY SOURCES

// =================================

if (verifySourcesButton) {

    verifySourcesButton.addEventListener(

        "click",

        function () {

            const topic =
                searchInput.value.trim();


            if (topic === "") {

                alert(
                    "Please search for a topic first."
                );

                return;

            }


            window.location.href =
                "verify.html?topic=" +

                encodeURIComponent(topic);

        }

    );

}



// =================================
// LOCAL SEARCH HISTORY

// =================================

function saveSearchHistory(query) {

    let history =
        JSON.parse(

            localStorage.getItem(
                "nexoraSearchHistory"
            )

        ) || [];


    history.unshift(query);


    history =
        history.slice(0, 10);


    localStorage.setItem(

        "nexoraSearchHistory",

        JSON.stringify(history)

    );


    localStorage.setItem(

        "nexoraSearchCount",

        history.length

    );

}



// =================================
// DEBUG USER

// =================================

console.log(
    "NEXORA User ID:",
    getNexoraUserId()
);


// =================================
// NEXORA SHORT NOTES

const shortNotesClass = document.getElementById("shortNotesClass");
const shortNotesSubject = document.getElementById("shortNotesSubject");
const shortNotesBook = document.getElementById("shortNotesBook");
const shortNotesChapter = document.getElementById("shortNotesChapter");
const shortNotesExam = document.getElementById("shortNotesExam");
const shortNotesLanguage = document.getElementById("shortNotesLanguage");
const shortNotesMode = document.getElementById("shortNotesMode");
const shortNotesButton = document.getElementById("shortNotesButton");
const shortNotesStatus = document.getElementById("shortNotesStatus");
const shortNotesCustomFields = document.getElementById("shortNotesCustomFields");
const shortNotesCustomBook = document.getElementById("shortNotesCustomBook");
const shortNotesCustomChapter = document.getElementById("shortNotesCustomChapter");

let shortNotesManifest = {};

async function loadShortNotesManifest() {
    try {
        const response = await fetch("/api/short-notes/manifest");
        const data = await response.json();
        if (!response.ok || !data.success) throw new Error(data.message || "Manifest error");
        shortNotesManifest = data.manifest || {};
        populateShortNotesBooks();
    } catch (error) {
        console.error("NEXORA Short Notes Manifest Error:", error);
        if (shortNotesStatus) shortNotesStatus.textContent = "Unable to load books.";
    }
}

function getShortNotesClassData() {
    const classKey = shortNotesClass ? shortNotesClass.value : "";
    const manifestKey = classKey.toLowerCase().replace(/\s+/g, "");
    return shortNotesManifest[classKey] || shortNotesManifest[manifestKey] || null;
}

function getShortNotesSubjectData() {
    const classData = getShortNotesClassData();
    const subjectKey = shortNotesSubject ? shortNotesSubject.value : "";
    if (!classData || !classData.subjects) return null;
    return classData.subjects[subjectKey] || classData.subjects[subjectKey.toLowerCase()] || null;
}

function populateShortNotesBooks() {
    if (!shortNotesBook) return;

    shortNotesBook.innerHTML = "<option value=\"\">Select Book</option><option value=\"custom\">Custom / Other Book</option>";
    if (shortNotesChapter) shortNotesChapter.innerHTML = "<option value=\"\">Select Chapter</option><option value=\"custom\">Custom / Other Chapter</option>";

    const subjectData = getShortNotesSubjectData();
    if (!subjectData || !subjectData.books) {
        updateShortNotesCustomFields();
        return;
    }

    Object.entries(subjectData.books).forEach(([bookId, book]) => {
        const option = document.createElement("option");
        option.value = bookId;
        option.textContent = book.titleEn || book.titleHi || bookId;
        shortNotesBook.appendChild(option);
    });

    updateShortNotesCustomFields();
}

function populateShortNotesChapters() {
    if (!shortNotesChapter) return;

    shortNotesChapter.innerHTML = "<option value=\"\">Select Chapter</option><option value=\"custom\">Custom / Other Chapter</option>";

    const subjectData = getShortNotesSubjectData();
    const bookId = shortNotesBook ? shortNotesBook.value : "";
    const book = subjectData && subjectData.books ? subjectData.books[bookId] : null;

    if (!book || !Array.isArray(book.chapters)) {
        updateShortNotesCustomFields();
        return;
    }

    book.chapters.forEach(chapter => {
        const option = document.createElement("option");
        option.value = String(chapter.number);
        option.textContent = chapter.number + ". " + (chapter.titleEn || chapter.titleHi || "");
        shortNotesChapter.appendChild(option);
    });

    updateShortNotesCustomFields();
}

function updateShortNotesCustomFields() {
    if (!shortNotesCustomFields) return;
    const show = (shortNotesBook && shortNotesBook.value === "custom") || (shortNotesChapter && shortNotesChapter.value === "custom");
    shortNotesCustomFields.style.display = show ? "block" : "none";
}

if (shortNotesClass) shortNotesClass.addEventListener("change", populateShortNotesBooks);
if (shortNotesSubject) shortNotesSubject.addEventListener("change", populateShortNotesBooks);
if (shortNotesBook) shortNotesBook.addEventListener("change", populateShortNotesChapters);
if (shortNotesChapter) shortNotesChapter.addEventListener("change", updateShortNotesCustomFields);

if (shortNotesButton) {
    shortNotesButton.addEventListener("click", async () => {
        const className = shortNotesClass ? shortNotesClass.value.trim() : "";
        const subject = shortNotesSubject ? shortNotesSubject.value.trim() : "";
        const bookValue = shortNotesBook ? shortNotesBook.value : "";
        const chapterValue = shortNotesChapter ? shortNotesChapter.value : "";
        const exam = shortNotesExam ? shortNotesExam.value : "UPSC";
        const language = shortNotesLanguage ? shortNotesLanguage.value : "english";
        const mode = shortNotesMode ? shortNotesMode.value : "exam";
        const customBook = shortNotesCustomBook ? shortNotesCustomBook.value.trim() : "";
        const customChapter = shortNotesCustomChapter ? shortNotesCustomChapter.value.trim() : "";

        if (!className) return shortNotesStatus.textContent = "Please select Class.";
        if (!subject) return shortNotesStatus.textContent = "Please select Subject.";
        if (!bookValue) return shortNotesStatus.textContent = "Please select Book.";
        if (bookValue === "custom" && !customBook) return shortNotesStatus.textContent = "Please enter Book name.";
        if (!chapterValue) return shortNotesStatus.textContent = "Please select Chapter.";
        if (chapterValue === "custom" && !customChapter) return shortNotesStatus.textContent = "Please enter Chapter name.";

        const requestBody = {
            className,
            subject,
            bookId: bookValue === "custom" ? "" : bookValue,
            bookTitle: bookValue === "custom" ? customBook : "",
            chapter: chapterValue === "custom" ? "" : chapterValue,
            chapterTitle: chapterValue === "custom" ? customChapter : "",
            exam,
            language,
            mode
        };

        shortNotesButton.disabled = true;
        shortNotesStatus.textContent = "Generating Short Notes PDF...";

        try {
            const response = await fetch("/api/short-notes", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(requestBody)
            });

            if (!response.ok) {
                let message = "Failed to generate PDF.";
                try {
                    const data = await response.json();
                    message = data.message || data.error || message;
                } catch (_) {}
                throw new Error(message);
            }

            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = url;
            link.download = "NEXORA-Short-Notes-" + className.replace(/\s+/g, "-") + "-" + language + ".pdf";
            document.body.appendChild(link);
            link.click();
            link.remove();
            window.URL.revokeObjectURL(url);
            shortNotesStatus.textContent = "PDF generated successfully.";
        } catch (error) {
            console.error("NEXORA Short Notes Error:", error);
            shortNotesStatus.textContent = error.message || "Unable to generate PDF.";
        } finally {
            shortNotesButton.disabled = false;
        }
    });
}

loadShortNotesManifest();

// =================================
// NEXORA PYQ & TEST SERIES

// =================================

const pyqSubject =
    document.getElementById("pyqSubject");

const pyqExam =
    document.getElementById("pyqExam");

const pyqType =
    document.getElementById("pyqType");

const pyqLanguage =
    document.getElementById("pyqLanguage");

const pyqYear =
    document.getElementById("pyqYear");

const pyqTopic =
    document.getElementById("pyqTopic");

const pyqButton =
    document.getElementById("pyqButton");

const testSeriesButton =
    document.getElementById("testSeriesButton");

const pyqTestStatus =
    document.getElementById("pyqTestStatus");


// =================================
// NEXORA GENERIC PYQ SUBJECTS
// =================================

const pyqSubjectsByExam = {
    upsc: [
        ["geography", "Geography"],
        ["polity", "Polity"],
        ["history", "History"],
        ["economy", "Economy"],
        ["environment", "Environment"],
        ["science", "Science & Technology"],
        ["current-affairs", "Current Affairs"]
    ],

    ssc: [
        ["general-awareness", "General Awareness"],
        ["reasoning", "Reasoning"],
        ["quantitative-aptitude", "Quantitative Aptitude"],
        ["english", "English"]
    ],

    jee: [
        ["physics", "Physics"],
        ["chemistry", "Chemistry"],
        ["mathematics", "Mathematics"]
    ],

    neet: [
        ["physics", "Physics"],
        ["chemistry", "Chemistry"],
        ["biology", "Biology"]
    ],

    college: [
        ["computer-science", "Computer Science"],
        ["mathematics", "Mathematics"],
        ["physics", "Physics"],
        ["chemistry", "Chemistry"],
        ["other", "Other"]
    ]
};


function updatePYQSubjects() {

    if (!pyqSubject || !pyqExam) {
        return;
    }

    const exam =
        pyqExam.value || "upsc";

    const subjects =
        pyqSubjectsByExam[exam] ||
        pyqSubjectsByExam.upsc;

    pyqSubject.innerHTML = "";

    subjects.forEach(([value, label]) => {

        const option =
            document.createElement("option");

        option.value = value;
        option.textContent = label;

        pyqSubject.appendChild(option);

    });

}


// Update subjects when exam changes

if (pyqExam) {

    pyqExam.addEventListener(
        "change",
        updatePYQSubjects
    );

}


// =================================
// NEXORA GENERIC PYQ TOPICS
// =================================

const pyqTopicsBySubject = {

    geography: [
        ["", "All Chapters"],
        ["physical-geography", "Physical Geography"],
        ["geomorphology", "Geomorphology"],
        ["earth-interior", "Interior of the Earth"],
        ["plate-tectonics", "Plate Tectonics"],
        ["rocks-minerals", "Rocks & Minerals"],
        ["landforms", "Landforms"],
        ["climatology", "Climatology"],
        ["atmosphere", "Atmosphere"],
        ["solar-radiation", "Solar Radiation & Heat Balance"],
        ["atmospheric-circulation", "Atmospheric Circulation"],
        ["weather-systems", "Weather Systems"],
        ["oceanography", "Oceanography"],
        ["ocean-movements", "Movements of Ocean Water"],
        ["biodiversity", "Biodiversity"],
        ["indian-physiography", "India: Structure & Physiography"],
        ["drainage", "Drainage System"],
        ["indian-climate", "Indian Climate"],
        ["natural-vegetation", "Natural Vegetation"],
        ["soils", "Soils"],
        ["agriculture", "Agriculture"],
        ["minerals", "Mineral Resources"],
        ["industries", "Industries"],
        ["transport", "Transport & Communication"],
        ["population", "Population"],
        ["urbanization", "Urbanization"],
        ["regional-planning", "Regional Planning"],
        ["disasters", "Natural Hazards & Disasters"],
        ["mapping-gis", "Mapping, GIS & Remote Sensing"]
    ],

    polity: [
        ["", "All Chapters"],
        ["constitution", "Constitution"],
        ["making-of-constitution", "Making of the Constitution"],
        ["constitutional-features", "Constitutional Features"],
        ["citizenship", "Citizenship"],
        ["fundamental-rights", "Fundamental Rights"],
        ["dpsp", "Directive Principles"],
        ["fundamental-duties", "Fundamental Duties"],
        ["amendment", "Constitutional Amendments"],
        ["basic-structure", "Basic Structure"],
        ["president", "President"],
        ["vice-president", "Vice-President"],
        ["prime-minister", "Prime Minister & Council of Ministers"],
        ["parliament", "Parliament"],
        ["supreme-court", "Supreme Court"],
        ["high-courts", "High Courts"],
        ["judiciary", "Judiciary"],
        ["federalism", "Federalism"],
        ["centre-state", "Centre-State Relations"],
        ["local-government", "Local Government"],
        ["elections", "Elections"],
        ["constitutional-bodies", "Constitutional Bodies"],
        ["statutory-bodies", "Statutory & Regulatory Bodies"],
        ["emergency", "Emergency Provisions"],
        ["governance", "Governance"]
    ],

    history: [
        ["", "All Chapters"],
        ["prehistory", "Prehistory"],
        ["indus-valley", "Indus Valley Civilization"],
        ["vedic-age", "Vedic Age"],
        ["mahajanapadas", "Mahajanapadas"],
        ["buddhism-jainism", "Buddhism & Jainism"],
        ["maurya", "Mauryan Empire"],
        ["post-maurya", "Post-Mauryan Period"],
        ["gupta", "Gupta Period"],
        ["sangam", "Sangam Age"],
        ["ancient-art-culture", "Ancient Art & Culture"],
        ["delhi-sultanate", "Delhi Sultanate"],
        ["mughal", "Mughal Empire"],
        ["bhakti-sufi", "Bhakti & Sufi Movements"],
        ["regional-kingdoms", "Regional Kingdoms"],
        ["medieval-culture", "Medieval Art & Culture"],
        ["europeans", "Arrival of Europeans"],
        ["british-expansion", "British Expansion"],
        ["constitutional-acts", "Constitutional Acts"],
        ["social-religious-reform", "Social & Religious Reform"],
        ["revolt-1857", "Revolt of 1857"],
        ["nationalism", "Indian Nationalism"],
        ["gandhian-era", "Gandhian Era"],
        ["revolutionary-movement", "Revolutionary Movement"],
        ["independence-partition", "Independence & Partition"],
        ["industrial-revolution", "Industrial Revolution"],
        ["french-revolution", "French Revolution"],
        ["russian-revolution", "Russian Revolution"],
        ["world-wars", "World Wars"],
        ["imperialism", "Imperialism & Colonialism"],
        ["decolonization", "Decolonization"],
        ["cold-war", "Cold War"]
    ],

    economy: [
        ["", "All Chapters"],
        ["basic-concepts", "Basic Economic Concepts"],
        ["national-income", "National Income"],
        ["economic-growth", "Economic Growth"],
        ["economic-development", "Economic Development"],
        ["inflation", "Inflation"],
        ["unemployment", "Unemployment"],
        ["poverty", "Poverty"],
        ["inclusive-growth", "Inclusive Growth"],
        ["fiscal-policy", "Fiscal Policy"],
        ["monetary-policy", "Monetary Policy"],
        ["banking", "Banking"],
        ["financial-markets", "Financial Markets"],
        ["taxation", "Taxation"],
        ["budget", "Union Budget"],
        ["public-finance", "Public Finance"],
        ["external-sector", "External Sector"],
        ["balance-payments", "Balance of Payments"],
        ["exchange-rate", "Exchange Rate"],
        ["agriculture-economy", "Agriculture Economy"],
        ["industry", "Industry"],
        ["infrastructure", "Infrastructure"],
        ["planning", "Planning"],
        ["financial-inclusion", "Financial Inclusion"]
    ],

    environment: [
        ["", "All Chapters"],
        ["ecology", "Ecology"],
        ["ecosystem", "Ecosystem"],
        ["food-chain", "Food Chain & Food Web"],
        ["ecological-cycles", "Biogeochemical Cycles"],
        ["biodiversity", "Biodiversity"],
        ["species", "Species & Endemism"],
        ["conservation", "Biodiversity Conservation"],
        ["protected-areas", "Protected Areas"],
        ["forests", "Forests"],
        ["wetlands", "Wetlands"],
        ["marine-ecosystems", "Marine Ecosystems"],
        ["climate-change", "Climate Change"],
        ["pollution", "Pollution"],
        ["environmental-laws", "Environmental Laws"],
        ["eia", "Environmental Impact Assessment"],
        ["international-conventions", "International Environmental Conventions"],
        ["sustainable-development", "Sustainable Development"]
    ],

    science: [
        ["", "All Chapters"],
        ["physics-basics", "Physics Basics"],
        ["chemistry-basics", "Chemistry Basics"],
        ["biology-basics", "Biology Basics"],
        ["space", "Space Technology"],
        ["astronomy", "Astronomy"],
        ["biotechnology", "Biotechnology"],
        ["genetics", "Genetics"],
        ["health-disease", "Health & Diseases"],
        ["nuclear", "Nuclear Technology"],
        ["energy", "Energy Technology"],
        ["nanotechnology", "Nanotechnology"],
        ["computers", "Computers & Digital Technology"],
        ["artificial-intelligence", "Artificial Intelligence"],
        ["telecommunication", "Telecommunication"],
        ["defence-technology", "Defence Technology"]
    ],

    "current-affairs": [
        ["", "All Chapters"],
        ["national", "National Affairs"],
        ["international", "International Affairs"],
        ["polity-governance", "Polity & Governance"],
        ["economy", "Economy"],
        ["environment", "Environment"],
        ["science-technology", "Science & Technology"],
        ["security", "Internal Security"],
        ["reports-indices", "Reports & Indices"],
        ["international-organizations", "International Organizations"],
        ["places-in-news", "Places in News"],
        ["government-schemes", "Government Schemes"],
        ["awards", "Awards & Honours"]
    ],

    "general-awareness": [
        ["", "All Chapters"],
        ["history", "History"],
        ["geography", "Geography"],
        ["polity", "Indian Polity"],
        ["economy", "Economy"],
        ["general-science", "General Science"],
        ["static-gk", "Static GK"],
        ["current-affairs", "Current Affairs"],
        ["art-culture", "Art & Culture"],
        ["sports", "Sports"]
    ],

    reasoning: [
        ["", "All Chapters"],
        ["analogy", "Analogy"],
        ["classification", "Classification"],
        ["series", "Number & Alphabet Series"],
        ["coding-decoding", "Coding-Decoding"],
        ["blood-relations", "Blood Relations"],
        ["direction-sense", "Direction Sense"],
        ["ranking", "Ranking & Order"],
        ["syllogism", "Syllogism"],
        ["venn-diagram", "Venn Diagram"],
        ["statement-conclusion", "Statement & Conclusion"],
        ["puzzles", "Puzzles"],
        ["seating-arrangement", "Seating Arrangement"],
        ["clock-calendar", "Clock & Calendar"],
        ["non-verbal", "Non-Verbal Reasoning"]
    ],

    "quantitative-aptitude": [
        ["", "All Chapters"],
        ["number-system", "Number System"],
        ["hcf-lcm", "HCF & LCM"],
        ["simplification", "Simplification"],
        ["percentage", "Percentage"],
        ["ratio", "Ratio & Proportion"],
        ["average", "Average"],
        ["profit-loss", "Profit & Loss"],
        ["simple-interest", "Simple Interest"],
        ["compound-interest", "Compound Interest"],
        ["time-work", "Time & Work"],
        ["pipes-cisterns", "Pipes & Cisterns"],
        ["speed-distance", "Speed, Time & Distance"],
        ["boats-streams", "Boats & Streams"],
        ["algebra", "Algebra"],
        ["geometry", "Geometry"],
        ["mensuration", "Mensuration"],
        ["trigonometry", "Trigonometry"],
        ["statistics", "Statistics"],
        ["data-interpretation", "Data Interpretation"]
    ],

    english: [
        ["", "All Chapters"],
        ["parts-of-speech", "Parts of Speech"],
        ["tenses", "Tenses"],
        ["subject-verb", "Subject-Verb Agreement"],
        ["articles", "Articles"],
        ["prepositions", "Prepositions"],
        ["voice", "Active & Passive Voice"],
        ["narration", "Direct & Indirect Speech"],
        ["error-spotting", "Error Spotting"],
        ["sentence-improvement", "Sentence Improvement"],
        ["vocabulary", "Vocabulary"],
        ["synonyms-antonyms", "Synonyms & Antonyms"],
        ["idioms", "Idioms & Phrases"],
        ["one-word", "One Word Substitution"],
        ["cloze-test", "Cloze Test"],
        ["reading-comprehension", "Reading Comprehension"],
        ["para-jumbles", "Para Jumbles"]
    ],

    physics: [
        ["", "All Chapters"],
        ["units-measurements", "Units & Measurements"],
        ["vectors", "Vectors"],
        ["kinematics", "Kinematics"],
        ["laws-of-motion", "Laws of Motion"],
        ["work-energy-power", "Work, Energy & Power"],
        ["rotational-motion", "Rotational Motion"],
        ["gravitation", "Gravitation"],
        ["properties-of-matter", "Properties of Matter"],
        ["thermodynamics", "Thermodynamics"],
        ["kinetic-theory", "Kinetic Theory"],
        ["oscillations", "Oscillations"],
        ["waves", "Waves"],
        ["electrostatics", "Electrostatics"],
        ["capacitance", "Capacitance"],
        ["current-electricity", "Current Electricity"],
        ["magnetism", "Magnetic Effects of Current"],
        ["emi-ac", "Electromagnetic Induction & AC"],
        ["em-waves", "Electromagnetic Waves"],
        ["ray-optics", "Ray Optics"],
        ["wave-optics", "Wave Optics"],
        ["dual-nature", "Dual Nature of Matter"],
        ["atoms-nuclei", "Atoms & Nuclei"],
        ["semiconductors", "Semiconductors"],
        ["experimental-skills", "Experimental Physics"]
    ],

    chemistry: [
        ["", "All Chapters"],
        ["mole-concept", "Some Basic Concepts / Mole Concept"],
        ["atomic-structure", "Atomic Structure"],
        ["periodicity", "Periodic Classification"],
        ["chemical-bonding", "Chemical Bonding"],
        ["states-of-matter", "States of Matter"],
        ["thermodynamics", "Thermodynamics"],
        ["equilibrium", "Equilibrium"],
        ["redox", "Redox Reactions"],
        ["solutions", "Solutions"],
        ["electrochemistry", "Electrochemistry"],
        ["chemical-kinetics", "Chemical Kinetics"],
        ["surface-chemistry", "Surface Chemistry"],
        ["s-block", "s-Block Elements"],
        ["p-block", "p-Block Elements"],
        ["d-f-block", "d- and f-Block Elements"],
        ["coordination", "Coordination Compounds"],
        ["metallurgy", "Metallurgy"],
        ["organic-basics", "Organic Chemistry Basics"],
        ["hydrocarbons", "Hydrocarbons"],
        ["haloalkanes", "Haloalkanes & Haloarenes"],
        ["alcohols-phenols-ethers", "Alcohols, Phenols & Ethers"],
        ["aldehydes-ketones-acids", "Aldehydes, Ketones & Carboxylic Acids"],
        ["amines", "Amines"],
        ["biomolecules", "Biomolecules"],
        ["polymers", "Polymers"],
        ["practical-chemistry", "Practical Chemistry"]
    ],

    mathematics: [
        ["", "All Chapters"],
        ["sets-relations", "Sets, Relations & Functions"],
        ["complex-numbers", "Complex Numbers"],
        ["quadratic-equations", "Quadratic Equations"],
        ["sequence-series", "Sequences & Series"],
        ["permutations-combinations", "Permutations & Combinations"],
        ["binomial", "Binomial Theorem"],
        ["probability", "Probability & Statistics"],
        ["matrices-determinants", "Matrices & Determinants"],
        ["straight-lines", "Straight Lines"],
        ["circles", "Circles"],
        ["conics", "Conic Sections"],
        ["vectors", "Vector Algebra"],
        ["three-dimensional", "Three Dimensional Geometry"],
        ["limits", "Limits & Continuity"],
        ["differentiation", "Differentiation"],
        ["applications-derivatives", "Applications of Derivatives"],
        ["integration", "Integral Calculus"],
        ["differential-equations", "Differential Equations"],
        ["trigonometry", "Trigonometry"]
    ],

    biology: [
        ["", "All Chapters"],
        ["diversity", "Diversity in Living World"],
        ["plant-anatomy", "Structural Organisation in Plants"],
        ["animal-anatomy", "Structural Organisation in Animals"],
        ["cell-biology", "Cell Structure & Function"],
        ["biomolecules", "Biomolecules"],
        ["plant-physiology", "Plant Physiology"],
        ["human-physiology", "Human Physiology"],
        ["reproduction", "Reproduction"],
        ["genetics", "Genetics & Heredity"],
        ["evolution", "Evolution"],
        ["human-health", "Human Health & Disease"],
        ["biology-welfare", "Biology & Human Welfare"],
        ["biotechnology", "Biotechnology"],
        ["ecology", "Ecology"],
        ["biodiversity", "Biodiversity & Conservation"]
    ],

    "computer-science": [
        ["", "All Chapters"],
        ["programming", "Programming Fundamentals"],
        ["oop", "Object-Oriented Programming"],
        ["data-structures", "Data Structures"],
        ["algorithms", "Algorithms"],
        ["dbms", "Database Management Systems"],
        ["operating-systems", "Operating Systems"],
        ["computer-networks", "Computer Networks"],
        ["computer-architecture", "Computer Architecture"],
        ["software-engineering", "Software Engineering"],
        ["theory-computation", "Theory of Computation"],
        ["compiler-design", "Compiler Design"],
        ["artificial-intelligence", "Artificial Intelligence"],
        ["machine-learning", "Machine Learning"],
        ["web-development", "Web Development"],
        ["cybersecurity", "Cybersecurity"],
        ["cloud-computing", "Cloud Computing"],
        ["distributed-systems", "Distributed Systems"]
    ],

    other: [
        ["", "All Chapters"]
    ]
};

function updatePYQTopics() {

    if (!pyqTopic || !pyqSubject) {
        return;
    }

    const subject =
        pyqSubject.value || "geography";

    const topics =
        pyqTopicsBySubject[subject] ||
        [["", "All Topics"]];

    pyqTopic.innerHTML = "";

    topics.forEach(([value, label]) => {

        const option =
            document.createElement("option");

        option.value = value;
        option.textContent = label;

        pyqTopic.appendChild(option);

    });

}


if (pyqSubject) {

    pyqSubject.addEventListener(
        "change",
        updatePYQTopics
    );

}


// Initial subject + topic list

updatePYQSubjects();
updatePYQTopics();



// =================================
// LOAD PYQs

// =================================

async function loadPYQs() {

    if (!pyqSubject || !pyqButton) {
        return;
    }

    const subject =
        pyqSubject.value;

    const exam =
        pyqExam
            ? pyqExam.value
            : "upsc";

    const type =
        pyqType
            ? pyqType.value
            : "prelims";

    const language =
        pyqLanguage
            ? pyqLanguage.value
            : "bilingual";

    const year =
        pyqYear
            ? pyqYear.value
            : "";

    const topic =
        pyqTopic
            ? pyqTopic.value
            : "";


    pyqTestStatus.textContent =
        "Loading UPSC PYQs...";


    try {

        console.log("NEXORA PYQ REQUEST:", subject, exam, type, language, year, topic);
        const response =
            await fetch(
                "/api/pyq?subject=" +
                encodeURIComponent(subject) +
                "&exam=" +
                encodeURIComponent(exam) +
                "&type=" +
                encodeURIComponent(type) +
                "&language=" +
                encodeURIComponent(language) +
                "&year=" +
                encodeURIComponent(year) +
                "&topic=" +
                encodeURIComponent(topic)
            );


        if (!response.ok) {

            throw new Error(
                "Unable to load PYQs."
            );

        }


        const data =
            await response.json();


        if (!data.success) {

            throw new Error(
                data.message ||
                "PYQ loading failed."
            );

        }


        console.log("NEXORA PYQ CHECK:", data.success, data.total, data.questions, data.language);
        displayPYQs(data);


    } catch (error) {

        console.error(
            "NEXORA PYQ Error:",
            error
        );

        pyqTestStatus.textContent =
            error.message ||
            "Unable to load PYQs.";

    }

}



// =================================
// DISPLAY PYQs

// =================================

function displayPYQs(data) {

    let container =
        document.getElementById(
            "nexoraPyqResults"
        );

    if (!container) {

        container =
            document.createElement("section");

        container.id =
            "nexoraPyqResults";

        container.className =
            "answer-card";

        const pyqCard =
            document.querySelector(
                ".pyq-test-card"
            );

        if (pyqCard) {
            pyqCard.appendChild(
                container
            );
        } else {
            document.body.appendChild(
                container
            );
        }
    }

    container.innerHTML = "";

    const selectedLanguage =
        String(data.language || "bilingual")
            .toLowerCase();

    const heading =
        document.createElement("h2");

    heading.textContent =
        "📚 UPSC Previous Year Questions";

    container.appendChild(
        heading
    );

    if (
        !data.questions ||
        data.questions.length === 0
    ) {

        const empty =
            document.createElement("p");

        empty.textContent =
            data.message ||
            "No PYQs available for this selection.";

        container.appendChild(
            empty
        );

        if (pyqTestStatus) {
            pyqTestStatus.textContent =
                "No PYQs available.";
        }

        return;
    }

    data.questions.forEach(
        (q, index) => {

            const card =
                document.createElement("div");

            card.style.marginTop =
                "20px";

            card.style.padding =
                "18px";

            card.style.border =
                "1px solid #ddd";

            card.style.borderRadius =
                "12px";

            // =========================
            // META
            // =========================

            const meta =
                document.createElement("p");

            meta.textContent =
                q.year +
                " • " +
                String(q.type || "")
                    .toUpperCase() +
                " • " +
                q.source;

            card.appendChild(
                meta
            );

            // =========================
            // QUESTION
            // =========================

            const question =
                document.createElement("h3");

            question.textContent =
                (index + 1) +
                ". " +
                (
                    selectedLanguage === "hindi"
                        ? (
                            q.question_hi ||
                            "Hindi translation not available for this PYQ yet."
                        )
                        : q.question
                );

            card.appendChild(
                question
            );

            // =========================
            // BILINGUAL QUESTION
            // =========================

            if (
                selectedLanguage === "bilingual" &&
                q.question_hi
            ) {

                const hindiQuestion =
                    document.createElement("p");

                hindiQuestion.style.marginTop =
                    "8px";

                hindiQuestion.style.fontWeight =
                    "600";

                hindiQuestion.textContent =
                    "हिंदी: " +
                    q.question_hi;

                card.appendChild(
                    hindiQuestion
                );
            }

            if (
                selectedLanguage === "bilingual" &&
                !q.question_hi
            ) {

                const notice =
                    document.createElement("p");

                notice.style.marginTop =
                    "8px";

                notice.textContent =
                    "🇮🇳 Hindi translation not available for this PYQ yet.";

                card.appendChild(
                    notice
                );
            }

            // =========================
            // OPTIONS
            // =========================

            if (
                Array.isArray(q.options) &&
                q.options.length > 0
            ) {

                const options =
                    document.createElement("div");

                options.style.marginTop =
                    "12px";

                q.options.forEach(
                    option => {

                        const p =
                            document.createElement("p");

                        p.textContent =
                            option;

                        options.appendChild(
                            p
                        );
                    }
                );

                card.appendChild(
                    options
                );
            }

            // =========================
            // HINDI OPTIONS
            // =========================

            if (
                selectedLanguage === "bilingual" &&
                Array.isArray(q.options_hi) &&
                q.options_hi.length > 0
            ) {

                const hindiOptionsTitle =
                    document.createElement("p");

                hindiOptionsTitle.style.fontWeight =
                    "600";

                hindiOptionsTitle.textContent =
                    "हिंदी विकल्प:";

                card.appendChild(
                    hindiOptionsTitle
                );

                const hindiOptions =
                    document.createElement("div");

                q.options_hi.forEach(
                    option => {

                        const p =
                            document.createElement("p");

                        p.textContent =
                            option;

                        hindiOptions.appendChild(
                            p
                        );
                    }
                );

                card.appendChild(
                    hindiOptions
                );

            } else if (
                selectedLanguage === "bilingual" &&
                Array.isArray(q.options) &&
                q.options.length > 0 &&
                !q.options_hi
            ) {

                const notice =
                    document.createElement("p");

                notice.textContent =
                    "🇮🇳 Hindi options not available for this PYQ yet.";

                card.appendChild(
                    notice
                );
            }

            // =========================
            // HINDI-ONLY OPTIONS
            // =========================

            if (
                selectedLanguage === "hindi" &&
                Array.isArray(q.options_hi) &&
                q.options_hi.length > 0
            ) {

                const hindiOptions =
                    document.createElement("div");

                hindiOptions.style.marginTop =
                    "12px";

                q.options_hi.forEach(
                    option => {

                        const p =
                            document.createElement("p");

                        p.textContent =
                            option;

                        hindiOptions.appendChild(
                            p
                        );
                    }
                );

                card.appendChild(
                    hindiOptions
                );
            }

            // =========================
            // ANSWER
            // =========================

            const answerBox =
                document.createElement("div");

            answerBox.style.marginTop = "16px";
            answerBox.style.padding = "12px";
            answerBox.style.borderRadius = "10px";
            answerBox.style.background = "#f5f7fa";

            const answerTitle =
                document.createElement("strong");

            answerTitle.textContent =
                "Correct Answer";

            answerBox.appendChild(
                answerTitle
            );

            const answerText =
                document.createElement("p");

            answerText.style.marginBottom = "0";

            answerText.textContent =
                q.answer || "Answer not available yet.";

            answerBox.appendChild(
                answerText
            );

            card.appendChild(
                answerBox
            );

            // =========================
            // EXPLANATION
            // =========================

            if (q.explanation) {

                const explanationBox =
                    document.createElement("div");

                explanationBox.style.marginTop =
                    "12px";

                const explanationTitle =
                    document.createElement("strong");

                explanationTitle.textContent =
                    "Explanation";

                explanationBox.appendChild(
                    explanationTitle
                );

                const explanationText =
                    document.createElement("p");

                explanationText.textContent =
                    q.explanation;

                explanationBox.appendChild(
                    explanationText
                );

                card.appendChild(
                    explanationBox
                );
            }

            // =========================
            // NCERT CONNECTION
            //             =========================

            const details =
                document.createElement("p");

            details.style.marginTop =
                "12px";

            details.textContent =
                "NCERT: " +
                (q.ncert_book || "-") +
                " → " +
                (q.ncert_chapter || "-");

            card.appendChild(
                details
            );

            container.appendChild(
                card
            );
        }
    );

    if (pyqTestStatus) {
        pyqTestStatus.textContent =
            data.total +
            " PYQ(s) loaded successfully.";
    }
}


/* =================================
   NEXORA TEST SERIES ENGINE
================================= */

let activeTestQuestions = [];
let activeTestIndex = 0;
let activeTestScore = 0;

async function startTestSeries() {

    const subject = pyqSubject ? pyqSubject.value : "geography";
    const exam = pyqExam ? pyqExam.value : "upsc";
    const type = pyqType ? pyqType.value : "prelims";
    const language = pyqLanguage ? pyqLanguage.value : "bilingual";
    const year = pyqYear ? pyqYear.value : "";
    const topic = pyqTopic ? pyqTopic.value : "";

    if (pyqTestStatus) {
        pyqTestStatus.textContent = "🧠 Test Series loading...";
    }

    try {
        const response = await fetch(
            "/api/test-series?subject=" + encodeURIComponent(subject) +
            "&exam=" + encodeURIComponent(exam) +
            "&type=" + encodeURIComponent(type) +
            "&language=" + encodeURIComponent(language) +
            "&year=" + encodeURIComponent(year) +
            "&topic=" + encodeURIComponent(topic) +
            "&count=10"
        );

        const data = await response.json();

        if (!response.ok || !data.success) {
            throw new Error(data.message || "Test Series could not start.");
        }

        if (!data.questions || data.questions.length === 0) {
            if (pyqTestStatus) {
                pyqTestStatus.textContent =
                    "⚠️ Is selection ke liye Test Series dataset available nahi hai.";
            }
            return;
        }

        activeTestQuestions = data.questions;
        activeTestIndex = 0;
        activeTestScore = 0;

        renderTestQuestion();

    } catch (error) {
        console.error("NEXORA Test Series Error:", error);

        if (pyqTestStatus) {
            pyqTestStatus.textContent =
                "❌ Test Series start nahi ho saki: " + error.message;
        }
    }
}

function renderTestQuestion() {

    const container = document.getElementById("pyqResults");
    if (!container) return;

    const q = activeTestQuestions[activeTestIndex];

    if (!q) {
        finishTestSeries();
        return;
    }

    container.innerHTML = "";

    const card = document.createElement("div");
    card.className = "pyq-question-card";

    const number = document.createElement("div");
    number.className = "answer-label";
    number.textContent =
        "QUESTION " + (activeTestIndex + 1) +
        " / " + activeTestQuestions.length;

    const question = document.createElement("h3");
    question.textContent = q.question || "Question unavailable.";

    card.appendChild(number);
    card.appendChild(question);

    if (Array.isArray(q.options) && q.options.length > 0) {

        q.options.forEach(function(option, optionIndex) {

            const button = document.createElement("button");
            button.type = "button";
            button.className = "main-cta";
            button.style.display = "block";
            button.style.width = "100%";
            button.style.marginTop = "10px";
            button.textContent =
                String.fromCharCode(65 + optionIndex) + ". " + option;

            button.addEventListener("click", function() {

                const correct =
                    String(q.answer || "").trim().toLowerCase();

                const selected =
                    String(option || "").trim().toLowerCase();

                if (selected === correct) {
                    activeTestScore++;
                }

                activeTestIndex++;
                renderTestQuestion();
            });

            card.appendChild(button);
        });

    } else {

        const message = document.createElement("p");
        message.textContent =
            "⚠️ Is question ka MCQ options dataset mein available nahi hai.";
        card.appendChild(message);

        const nextButton = document.createElement("button");
        nextButton.type = "button";
        nextButton.className = "main-cta";
        nextButton.textContent = "Next Question →";

        nextButton.addEventListener("click", function() {
            activeTestIndex++;
            renderTestQuestion();
        });

        card.appendChild(nextButton);
    }

    container.appendChild(card);

    if (pyqTestStatus) {
        pyqTestStatus.textContent =
            "🧠 Test Series running — Question " +
            (activeTestIndex + 1) +
            " of " + activeTestQuestions.length;
    }
}

function finishTestSeries() {

    const container = document.getElementById("pyqResults");
    if (!container) return;

    const total = activeTestQuestions.length;
    const percentage = total > 0
        ? Math.round((activeTestScore / total) * 100)
        : 0;

    container.innerHTML =
        "<div class=\"pyq-question-card\">" +
        "<h2>🏆 Test Completed</h2>" +
        "<p><strong>Score:</strong> " + activeTestScore +
        " / " + total + "</p>" +
        "<p><strong>Percentage:</strong> " + percentage + "%</p>" +
        "<button type=\"button\" id=\"restartTestSeries\">" +
        "🔄 Start Test Again</button>" +
        "</div>";

    const restart =
        document.getElementById("restartTestSeries");

    if (restart) {
        restart.addEventListener("click", startTestSeries);
    }

    if (pyqTestStatus) {
        pyqTestStatus.textContent =
            "✅ Test completed successfully.";
    }
}

if (testSeriesButton) {
    testSeriesButton.addEventListener("click", startTestSeries);
}

if (pyqButton) {
    pyqButton.addEventListener("click", loadPYQs);
}
